name: BukkitComputer
description: A project for the Devathon contest
version: 1.0.0
author: MrToucan
commands:
    bukkitcomputer:
      description: Main Computer Command!

main: org.devathon.contest2016.DevathonPlugin

